controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 5.0
    progress_checker_plugin: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"] 
    controller_plugins: ["FollowPath"]
    odom_topic: "odom"
    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 3.1415 #0.7
    # Follow path parameters
    FollowPath: #FollowPathDWB
      plugin: "pytorch_controller::PyTorchController"
      pytorch_model_path: "/home/gjaeger/Documents/Programming/ICRAAnalysis/intermediate_results/rl_training/models/actor_actor.pt"
      max_angular_vel: 1.0
      transform_tolerance: 0.1
    