/monitor_node:
  ros__parameters:
    domain: navigation
    message_type: OccupancyGrid
    min_f: 0.25
    start_type_description_service: true
    topic_name: /global_costmap/costmap
    update_f: 1.0
    use_sim_time: false
